services:
  # 1. Web Server (PHP + Apache)
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  # 2. Database (MySQL)
  db:
    image: mysql:8.0
    container_name: db_kompetisi
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_lomba
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql

  # 3. phpMyAdmin (ADD THIS BLOCK)
  phpmyadmin:
    image: phpmyadmin
    container_name: pma_sparta
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=userpass
    depends_on:
      - db

volumes:
  db_data: